//
//  RomanGinti.swift
//  Number To Urdu Phrase
//
//  Created by Muhammad Abdullah on 21/06/2019.
//  Copyright © 2019 Muhammad Abdullah. All rights reserved.
//

enum RomanGinti:Int {
  case Sifr = 0
  case Aik
  case Dow
  case Teen
  case Chaar
  case Paanch
  case Chay
  case Saat
  case Aath
  case Nau
  case Das
  case Giarah
  case Barah
  case Terah
  case Chaudah
  case Pandrah
  case Solah
  case Satarah
  case Atharah
  case Unnees
  case Bees
  case Ikkees
  case Baais
  case Taees
  case Chaubees
  case Pachis
  case Chabbis
  case Stais
  case Athais
  case Untees
  case Tees
  case Iktees
  case Battis
  case Tantees
  case Chauntis
  case Pantees
  case Chatees
  case Santees
  case Arthees
  case Untaalis
  case Chalis
  case Iktalis
  case Bialis
  case Tantalis
  case Chavalis
  case Pantalis
  case Chiyalis
  case Santalis
  case Artalis
  case Unchaas
  case Pachas
  case Ikyavan
  case Bavan
  case Tarippan
  case Chawwan
  case Pachpan
  case Chappan
  case Stavan
  case Athavan
  case Unsathh
  case Saath
  case Iksath
  case Basath
  case Traisath
  case Chaunsath
  case Painsath
  case Chiyasath
  case Sarsath
  case Arsath
  case Unhattar
  case Sattar
  case Ikhattar
  case Behattar
  case Tihattar
  case Chauhattar
  case Pachattar
  case Chihattar
  case Sathattar
  case Athhattar
  case Unasi
  case Assi
  case Ikaasi
  case Bayasi
  case Tiraasi
  case Chaurassi
  case Pachaasi
  case Chiaasi
  case Sataasi
  case Athassi
  case Navassi
  case Navvay
  case Ikaanvey
  case Baanvay
  case Tiraanvay
  case Chauraanvay
  case Pachaanvay
  case Chiyaanvay
  case Sataanvay
  case Athaanvay
  case Ninaanvay
}
